const questions=[
    {
        q_id:1,
        title:"fdgr",
        body:"wefgwa",
        input_format :"gwrqrg",
        output_format :"gwrqrg",
        constraints :"gwrqrg",
        s_input :"gwrqrg",
        o_output :"gwrqrg",
        tc1 :"gwrqrg",
        tc2  :"gwrqrggwrqrg",
         tc3 :"gwrqrg",
        ans1 :"gwrqrg",
        ans2 :"gwrqrg",
        ans3:"fbea",
        score:100
    },
    {
        q_id:2,
        title:"fdgr",
        body:"wefgwa",
        input_format :"gwrqrg",
        output_format :"gwrqrg",
        constraints :"gwrqrg",
        s_input :"gwrqrg",
        o_output :"gwrqrg",
        tc1 :"gwrqrg",
        tc2  :"gwrqrggwrqrg",
         tc3 :"gwrqrg",
        ans1 :"gwrqrg",
        ans2 :"gwrqrg",
        ans3:"fbea",
        score:150
    },
    {
        q_id:3,
        title:"fdgr",
        body:"wefgwa",
        input_format :"gwrqrg",
        output_format :"gwrqrg",
        constraints :"gwrqrg",
        s_input :"gwrqrg",
        o_output :"gwrqrg",
        tc1 :"gwrqrg",
        tc2  :"gwrqrggwrqrg",
         tc3 :"gwrqrg",
        ans1 :"gwrqrg",
        ans2 :"gwrqrg",
        ans3:"fbea",
        score:200
    },
    {
        q_id:4,
        title:"fdgr",
        body:"wefgwa",
        input_format :"gwrqrg",
        output_format :"gwrqrg",
        constraints :"gwrqrg",
        s_input :"gwrqrg",
        o_output :"gwrqrg",
        tc1 :"gwrqrg",
        tc2  :"gwrqrggwrqrg",
         tc3 :"gwrqrg",
        ans1 :"gwrqrg",
        ans2 :"gwrqrg",
        ans3:"fbea",
        score:150
    },
    {
        q_id:5,
        title:"fdgr",
        body:"wefgwa",
        input_format :"gwrqrg",
        output_format :"gwrqrg",
        constraints :"gwrqrg",
        s_input :"gwrqrg",
        o_output :"gwrqrg",
        tc1 :"gwrqrg",
        tc2  :"gwrqrggwrqrg",
         tc3 :"gwrqrg",
        ans1 :"gwrqrg",
        ans2 :"gwrqrg",
        ans3:"fbea",
        score:250
    },
    {
        q_id:6,
        title:"fdgr",
        body:"wefgwa",
        input_format :"gwrqrg",
        output_format :"gwrqrg",
        constraints :"gwrqrg",
        s_input :"gwrqrg",
        o_output :"gwrqrg",
        tc1 :"gwrqrg",
        tc2  :"gwrqrggwrqrg",
         tc3 :"gwrqrg",
        ans1 :"gwrqrg",
        ans2 :"gwrqrg",
        ans3:"fbea",
        score:100
    },
    {
        q_id:7,
        title:"fdgr",
        body:"wefgwa",
        input_format :"gwrqrg",
        output_format :"gwrqrg",
        constraints :"gwrqrg",
        s_input :"gwrqrg",
        o_output :"gwrqrg",
        tc1 :"gwrqrg",
        tc2  :"gwrqrggwrqrg",
         tc3 :"gwrqrg",
        ans1 :"gwrqrg",
        ans2 :"gwrqrg",
        ans3:"fbea",
        score:100
    },
    {
        q_id:8,
        title:"fdgr",
        body:"wefgwa",
        input_format :"gwrqrg",
        output_format :"gwrqrg",
        constraints :"gwrqrg",
        s_input :"gwrqrg",
        o_output :"gwrqrg",
        tc1 :"gwrqrg",
        tc2  :"gwrqrggwrqrg",
         tc3 :"gwrqrg",
        ans1 :"gwrqrg",
        ans2 :"gwrqrg",
        ans3:"fbea",
        score:100
    }
];
export default questions;